name:                smt2-parser
version:             0.1.0.1
github:              "crvdgc/smt2-parser"
license:             BSD3
author:              "crvdgc"
maintainer:          "ubikium@gmail.com"
copyright:           "2020 crvdgc"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A Haskell parser for SMT-LIB version 2.6
category:            SMT, Formal Languages, Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/crvdgc/smt2-parser#readme>

dependencies:
- base >= 4.13.0 && < 5
- parsec >= 3.1.14
- text >= 1.2.4

library:
  source-dirs: src

tests:
  smt2-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smt2-parser
    - HUnit >= 1.6.0
